config/routes.rb
Rails.application.routes.draw do
  post '/homes/guest_sign_in', to: 'homes#guest_sign_in'
  devise_for :users
  root to: "homes#top"
  get 'lists/search', to: 'lists#search'
  resources :lists, only: [:new, :create, :index, :show, :edit, :destroy, :update] do
    resources :list_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
  resources :carts, only: [:index, :create, :update]
  resources :users, only: [:show, :edit, :update]
  resources :categories, only: [:index, :create, :edit, :update]
  resources :contacts, only: [:new, :create]
  post 'contacts/confirm', to: 'contacts#confirm', as: 'confirm'
  post 'contacts/back', to: 'contacts#back', as: 'back'
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :list
  belongs_to :user
  
  validates :amount, presence: true, numericality: {only_integer: true, greater_than_or_equal_to: 1}
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :lists 
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :name, presence: true
  validates :message, presence: true
  enum subject: { inquiry: 0, report: 1 }
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :list
  
  validates :user_id, uniqueness: {scope: :list_id}
end

app/models/list.rb
class List < ApplicationRecord
  has_one_attached :image
  belongs_to :user
  belongs_to :category
  has_many :list_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :carts, dependent: :destroy
  has_many :order_details 
  
  
  validates :title, presence: true
  validates :body, presence: true
  
  def fav_by?(user)
    favorites.exists?(user_id: user.id)
  end
  
  def get_image
    unless image.attached?
      file_path = Rails.root.join("app/assets/images/no_fhoto.jpg")
      image.attach(io: File.open(file_path), filename: "default-image.jpg", content_type: "image/jpeg")
    end
    image.variant(resize_to_limit: [500, 500]).processed
  end
end

app/models/list_comment.rb
class ListComment < ApplicationRecord
  belongs_to :user
  belongs_to :list
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_details
  belongs_to :user
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :list
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :lists, dependent: :destroy
  has_many :list_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :carts, dependent: :destroy
  has_many :orders
  
  validates :name, presence: true
  
  has_one_attached :profile_image
  
  def get_profile_image
    unless profile_image.attached?
      file_path = Rails.root.join("app/assets/images/no_person.jpg")
      profile_image.attach(io: File.open(file_path), filename: "sample-image.jpg", content_type: "image/jpeg")
    end
    profile_image.variant(resize_to_limit: [100, 100]).processed
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def index
    @carts = current_user.carts.all
  end 
    
  def create
    @cart = current_user.carts.new(cart_params)
    if current_user.carts.find_by(list_id: params[:cart][:list_id]).present?
      cart = current_user.carts.find_by(list_id: params[:cart][:list_id])
      cart.amount += params[:cart][:amount].to_i
      cart.update(amount: cart.amount)
      redirect_to carts_path
    else
      @cart.save
      @carts = current_user.carts.all
      redirect_to carts_path
    end
  end
  
  def update
    @cart = Cart.find(params[:id])
    @cart.update(cart_params)
    redirect_to carts_path
  end
  
  
  private
  
  def cart_params
    params.require(:cart).permit(:list_id, :amount, :user_id)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  
  def guest_sign_in
    user = User.find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "ゲスト"
    end
    sign_in user
    redirect_to root_path, notice: 'ゲストユーザーとしてログインしました。'
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def new
    @list = List.new
  end
  
  def create
    @list = List.new(list_params)
    @list.user_id = current_user.id
    if @list.save
      redirect_to list_path(@list.id)
    else
      render :new
    end
  end

  def index
    @categories = Category.all
    if params[:title].present?
       @lists = List.where('title LIKE(?)', "%#{params[:title]}")
    else
      @lists = List.page(params[:page]).order("created_at desc")
    end
  end

  def show
    @list = List.find(params[:id])
    @list_comment = ListComment.new
    @cart = Cart.new
  end

  def edit
    @list = List.find(params[:id])
  end
  
  def update
    @list = List.find(params[:id])
    if @list.update(list_params)
      redirect_to list_path(@list.id)
    else 
      redirect_to lists_path
    end
  end
  
  def destroy
    list = List.find(params[:id])
    list.destroy
    redirect_to lists_path
  end  
  
  def search
    @categories = Category.all
    @category = Category.find(params[:category_id])
    @lists = @category.lists
    render "index"
  end
  
  private
    def list_params
      params.require(:list).permit(:category_id, :title, :body, :image, :price, :is_deleted)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :is_maching_login_user, only: [:edit, :update]
  def show
    @user = User.find(params[:id])
    @lists = @user.lists
  end

  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to @user
    end
  end
  
  
  
  private
  
  def user_params
    params.require(:user).permit(:name, :profile_image)
  end
  
  def is_maching_login_user
    user = User.find(params[:id])
    unless user.id == current_user.id
      redirect_to root_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/list_comments_helper.rb
module ListCommentsHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/carts/index.html.erb
<% add_up = 0 %>
<h2>ショッピングカート</h2>
<table>
  <thead>
    <th>商品名</th>
    <th>単価</th>
    <th>個数</th>
    <th>小計</th>
  </thead>
  <tbody>
    <% @carts.each do |cart| %>
    <td><%= image_tag cart.list.get_image, size: "100x100" %><br />
        <%= cart.list.body %>
    </td>
  </tbody>
</table>

app/views/lists/edit.html.erb
<h1>編集画面</h1>
<%= form_with model: @list do |f| %>
  <h4>タイトル</h4>
  <%= f.text_field :title %>
  <h4>本文</h4>
  <%= f.text_area :body %>
  <h4>カテゴリ</h4>
   <label>カテゴリ</label>
  <%= f.collection_select :category_id, Category.all, :id, :name %>
  <h4>画像</h4>
  <%= image_tag @list.image, size: "100x100", id: :img_prev %> 
  <%= f.file_field :image, id: :list_image %>
  <%= f.submit "保存" %>
<% end %>

<script type="text/javascript">
  let reader = new FileReader();
  $(function(){
    function readURL(input){
      if (input.files && input.files[0]) {
        reader.onload = function (e) {
          $('#img_prev').attr('src', e.target.result);
        }
        reader.readAsDataURL(input.files[0]);
      }
    }
    $("#list_image").change(function(){
      readURL(this);  
    });
  });
</script>

app/views/lists/index.html.erb
<h1>投稿一覧</h1>
<%= form_with url: lists_path, method: :get do |f| %>
  <%= f.text_field :title %>
  <%= f.submit '検索' %>
<% end %>
<% @categories.each do |category| %>
  <%= link_to category.name, lists_search_path(category_id: category.id), method: :get %>
<% end %>
<% @lists.each do |list| %>
  <p>タイトル</p>
  <%= link_to list_path(list.id) do %>
    <%= list.title %>
  <% end %>
  <p>本文</p>
    <%= list.body %>
<% end %> 

app/views/lists/new.html.erb
<h1>新規投稿</h1>
<% if @list.errors.any? %>
  <%= @list.errors.count %>件のエラーが発生しました
  <ul>
    <% @list.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
<%= form_with model: @list do |f| %>
  <h4>タイトル</h4>
  <%= f.text_field :title %>
  <h4>本文</h4>
  <%= f.text_area :body %>
  <label>カテゴリ</label>
  <%= f.collection_select :category_id, Category.all, :id, :name %>
  <h4>画像</h4>
  <%= image_tag asset_path('no_fhoto.jpg'), size: "100x100", id: :img_prev %>
  <%= f.file_field :image, id:  :list_image %>
  <h4>価格</h4>
  <%= f.text_field :price %>円
  </br>
  <h4>公開/非公開</h4>
  <%= f.radio_button :is_deleted, false %>
  <%= f.label :is_deleted, "公開" %>
  <%= f.radio_button :is_deleted, true %>
  <%= f.label :is_deleted, "非公開" %>
  </br>
  <%= f.submit '投稿' %>
<% end %>

<script type="text/javascript">
  let reader = new FileReader();
  $(function(){
    function readURL(input) {
      if (input.files && input.files[0]) {
        reader.onload = function (e) {
          $('#img_prev').attr('src', e.target.result);
        }
        reader.readAsDataURL(input.files[0]);
      }
    }
    $("#list_image").change(function(){
      readURL(this);
    });
  }); 
</script>

app/views/lists/show.html.erb
<p><%= @list.title %></p>
<p><%= @list.body %></p>
<p><%= @list.category.name %></p>
<p><%= @list.price %>円</p>
<p><%= image_tag @list.get_image, size: "200x200" %> </p>
<%= button_to '削除', list_path(@list.id), :method => :delete %>
<br />
<%= link_to "編集画面へ", edit_list_path(@list.id) %>

<%= form_with model: @cart, url: carts_path, method: :post do |f| %>
  <% if @list.is_deleted == false %>
    <%= f.hidden_field :list_id, :value => @list.id %>
    <%= f.hidden_field :user_id, :value => current_user.id %>
    <%= f.select :amount, *[1..10] %>
    <%= f.submit 'カートに入れる' %>
  <% end %>
<% end %>

<div>
  <p>コメント件数：<%= @list.list_comments.count %></p>
  <% @list.list_comments.each do |list_comment| %>
    <p><%= image_tag list_comment.user.get_profile_image, size: "50x50" %></p>
    <%= list_comment.user.name %>
    <%= list_comment.created_at.strftime('%Y/%m/%d') %>
    <%= list_comment.comment %>
    <% if list_comment.user == current_user %>
      <%= button_to "削除", list_list_comment_path(list_comment.list, list_comment), :method => :delete %>
    <% end %>
  <% end %>
  <% if @list.fav_by?(current_user) %>
    <p>
      <%= button_to list_favorites_path(@list), :method => :delete do %>
        ♥<%= @list.favorites.count %> 
      <% end %>
    </p>
    <% else %>
    <p>
      <%= button_to list_favorites_path(@list), :method => :post do %>
        ♡<%= @list.favorites.count %>
      <% end %>
    </p>
  <% end %>
</div>
<div>
  <%= form_with model: [@list, @list_comment] do |f| %>
    <%= f.text_area :comment, placeholder: "コメントをここに" %>
    <%= f.submit "送信する" %>
  <% end %>
</div>

app/views/users/edit.html.erb
<h2>プロフィール編集</h2>
<%= form_with model: @user do |f| %>
  <label for="inputName">Name</label>
  <%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"名前"%>
  <label for="inputImage">ProfileImage</label>
  <%= image_tag @user.profile_image, size: "100x100", id: :img_prev %>
  <%= f.file_field :profile_image, id: :user_image, placeholder: "プロフィール画像", accept: "image/*" %>  
  <%= f.submit "変更を保存" %>
<% end %>

<script type="text/javascript">
  let reader = new FileReader();
  $(function(){
    function readURL(input){
      if (input.files && input.files[0]) {
        reader.onload = function (e) {
          $('#img_prev').attr('src', e.target.result);
        }
        reader.readAsDataURL(input.files[0]);
      }
    }
    $("#user_image").change(function(){
      readURL(this);  
    });
  });
</script>

app/views/users/show.html.erb
<div>
  <h3><%= @user.name %></h3>
  <%= image_tag @user.get_profile_image, size: "50x50" %>
  <% if @user == current_user %>
    <p><%= link_to "プロフィール編集", edit_user_path(@user) %></p>
  <% end %>
</div>

<h3><%= @user.name %>さんの投稿</h3>
<% @lists.each do |list| %>
<div>
  <%= link_to list_path(list.id) do %>
    <%= image_tag list.get_image %>
  <% end %>
  <p>投稿ユーザー画像：<%= image_tag list.user.get_profile_image, size: "50x50" %></p>
  <p>タイトル: <%= list.title %></p>
  <p>本文: <%= list.body %></p>
  <p>ユーザーネーム：<%= list.user.name %></p>
</div>
<% end %>